### ISSUE TITLE
Webshell-Detection-Tool

### ISSUE THREAD

**Issue by zhangchenyi88** [zhangchi991022/Webshell-Detection-Tool#1]
你这个具体需要的环境是什么，怎么一直运行不成功。有配置环境的具体要求吗？谢谢解答。或者说其他交流方式，请教一下你。

**Comment by zhangchi991022** [comment]
后端所有都是基于Python2.7和tensorflow 1.10，请问你现在的具体问题是什么呢

**Comment by zhangchenyi88** [comment]
你这个登录界面的用户名密码是多少




独行者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangchi991022/Webshell-Detection-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 下午5:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangchi991022/Webshell-Detection-Tool] Webshell-Detection-Tool (Issue #1)





 
后端所有都是基于Python2.7和tensorflow 1.10，请问你现在的具体问题是什么呢

**Comment by zhangchenyi88** [comment]
你这个登录注册界面是在那个模块书写。


独行者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangchi991022/Webshell-Detection-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 下午5:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangchi991022/Webshell-Detection-Tool] Webshell-Detection-Tool (Issue #1)





 
后端所有都是基于Python2.7和tensorflow 1.10，请问你现在的具体问题是什么呢

**Comment by zhangchi991022** [comment]
登录注册前端在templates/index，后端视图在index/view.py里面，登录的用户名和密码需要先注册

**Comment by zhangchenyi88** [comment]
Run id: webshell
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 0
Validation samples: 0
--
Exception in thread Thread-2:
Traceback (most recent call last):
&nbsp; File "d:\python\lib\threading.py", line 916, in _bootstrap_inner
&nbsp;&nbsp;&nbsp; self.run()
&nbsp; File "d:\python\lib\threading.py", line 864, in run
&nbsp;&nbsp;&nbsp; self._target(*self._args, **self._kwargs)
&nbsp; File "C:\Users\Administrator\Envs\CTF\lib\site-packages\tflearn\data_flow.py", line 201, in fill_batch_ids_queue
&nbsp;&nbsp;&nbsp; ids = self.next_batch_ids()
&nbsp; File "C:\Users\Administrator\Envs\CTF\lib\site-packages\tflearn\data_flow.py", line 215, in next_batch_ids
&nbsp;&nbsp;&nbsp; batch_start, batch_end = self.batches[self.batch_index]
IndexError: list index out of range



还是打扰你了，你在运行train的时候遇到这个错误了吗？

**Comment by zhangchi991022** [comment]
这个应该是列表索引越界了，发生在执行data_flow.py中batch_start, batch_end = self.batches[self.batch_index]
